<nav class="navbar navbar-default">
<div class="row">
<div class="col1">
<ul>
<li><a href="#">About us</a></li>
</ul>
</div>
<div class="col2">
<ul>
<li><a href="#">our stores</a></li>
</ul>
</div>
<div class="col3">
<ul>
<li><a href="#">offers</a></li>
</ul>
</div>
<ul>
<li class="dropdown"><a class="dropdown-toggle" href="#" data-toggle="dropdown">My Account </a>
<ul class="dropdown-menu">
<li><a href="#">Page 1-1</a></li>
<li><a href="#">Page 1-2</a></li>
<li><a href="#">Page 1-3</a></li>S
</ul>
</li>
</ul>
</div>
</nav>